### ISSUE TITLE
Specifiche di mapping per le richieste http

### ISSUE THREAD

**Issue by angelitadoria** [mainieritm/rubrica-telefonica#13]
**/conta** (richiama il metodo conta() che restituisce un CounterDto)
**/search** (richiama il metodo search() e restituisce ListaContattiDto)
**/cancella-rubrica** (restituisce ListaContattiDto)
**/aggiungi-rubrica** (restituisce ListaContattiDto)
**/mainpage** (restituisce ListaContattiDto)
**/login** (restituisce UtenteDto che all'interno avrà autenticato true o false)

**Comment by AndreaTangucci** [comment]
Risolto con commit 58f60a832e55a0d046adee52f9bd9b00deef1917
