### ISSUE TITLE
Creare Dto lato Client

### ISSUE THREAD

**Issue by AndreaTangucci** [mainieritm/rubrica-telefonica#3]

**Comment by angelitadoria** [comment]
ELENCO DTO:

**ContattoDto**
contatto: Contatto

**CounterDto**
numeroContatti: number

**CriterioRicercaDto**
stringa: string

**ListaContattiDto**
contatti: Contatto[]

**UtenteDto**
utente: Utente
autenticato: boolean

**Comment by LorenzoMariotti101** [comment]
Completato in Commit 7fb32304c2800bdb38e38c91459f5b3644f9ebc2
